# 1. Main Bot
      - name: Run Main Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

      # # 2. Bot Simulasi Trading (SMC + TECH) -> DINONAKTIFKAN
      # - name: Run Simulasi Trading
      #   env:
      #     TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      #   run: |
      #     python paper_trader.py

      # # 3. Commit & Push semua file JSON state paper trading -> DINONAKTIFKAN JUGA
      # - name: Save Paper Trading States
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action Bot"
      #     git add *.json || true
      #     git commit -m "Auto-update status paper trading [skip ci]" || true
      #     git push || true
